#Application Configuration
server:
  port: 8080
  
#==================================
#Configuración para Eureka
#==================================
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
            
#==================================
#Configuración para Gateway
#==================================         
spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: tienda-cliente
        uri: lb://tienda-cliente
        predicates:
          - Path=/clientes/**
      - id: tienda-producto
        uri: lb://tienda-producto
        predicates:
         - Path=/productos/**
      - id: tienda-compra
        uri: lb://tienda-compra
        predicates:
          - Path=/facturas/**