#Application Configuration
server:
  port: 8093
  
#To see H2 console in browser;
#http://localhost:8091/h2-console
#Enabling H2 console
spring:
  h2:
    console:
      enabled: true
      
#==================================
#DB cada microservicio tendrá su base de datos productDB y los otros tendrán otros
#=================================== 
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
    
#==================================
#JPA
#==================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5}" 
      
#==================================
#Configuración para Eureka
#==================================
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
            
#==================================
#Configuración para Hystrix
#==================================
Feign:
    hystrix:
        enabled: true

        
#==================================
#Configuración para Actuector
#==================================        
management:
    endpoints:
        web:
            exposure:
                include: "*"

